### PR TITLE
Add idempotency support in update() methods

### PR DESCRIPTION
**Pull request by sygilber**
Hi

Please review and consider for merge.

The update in the update() methods of following Python file will improve idempotency:
-http_transformation.py
-junction_mapping.py

Thanks

### CODE REVIEW

**Comment by ram-ibm** [comment]
Does this strip just the end of the file contents please? Looks like it - I'll merge once I verify. We don't want to mess with whitespace inside of the contents.

**Comment by sygilber** [comment]
I don’t believe the stripping is permanent. It is just for the duration of the test.

**Comment by ram-ibm** [comment]
Looks like I missed coding idempotency for these. Thanks for putting them in. I am adding a bit more logic to avoid an edge case.

**Comment by ram-ibm** [comment]
FYI - I changed tabs to spaces. Please avoid tabs.

**Pull request merged**
