### PR TITLE
Add name in log for certificate database creation

### PR DESCRIPTION
**Pull request by dal-ibm**
Hi Ram,

I'm wondering if it would be worth including the name of the database being created. Perhaps there's a reason you've not already done this - would you mind cluing me in?

Cheers,
David

### CODE REVIEW

**Comment by ram-ibm** [comment]
David - I typically would cut/paste the one line description provided in the REST API documentation to describe the particular function. My thinking was that the JSON contents can be examined in the logs using other options.

There is no issue with adding the certificate database name to the description we log. It will be helpful to understand your particular use case so we can address other functions as we go forward.

**Comment by dal-ibm** [comment]
Thanks, Ram. What are those other options for examining the operation? I'm looking to port a script which tries to be transparent about its actions, and would appreciate a similar level of transparency here (without trying to add `'{}'` to every log statement in this library).

Sample output of the current script is below. I'm not aiming for direct parity, but notice the clarity in which files and names are being touched.
```
Connecting to ISAM at 'https://lmi.mysecure.org'

Authentication policies
Updating U2F register policy 'urn:ibm:security:authentication:asf:u2f_register'
Updating U2F authenticate policy 'urn:ibm:security:authentication:asf:u2f_authenticate'

InfoMap Mapping rules
Directory 'mapping_rules' doesn't exist, no mapping rules uploaded

Template files
C/authsvc/authenticator/u2f/authenticate.html: Updating existing file
C/authsvc/authenticator/u2f/register.html: Updating existing file
C/mmfa/user/mgmt/mmfa/usc/manage.html: Updating existing file

Authentication mechanisms
No authentication mechanisms in manifest; skipping

Authentication policies
No authentication policies in manifest; skipping

Reverse proxy configuration
snippet-filter:/mga/sps/mga/user/mgmt/html/device/device_selection.html '*Security Token Registration</h3>': Creating stanza
snippet-filter:/mga/sps/mga/user/mgmt/html/device/device_selection.html '</body>': Creating stanza
```

**Comment by ram-ibm** [comment]
@dal-ibm - I could not figure out where this comment was, finally tracked it down to this closed pull request.

When you run the python code - there is log information that gets written out with that it is doing. Most of the messages come from the isamappliance class. That class has access to all the data that has been passed to it.

Now normally we use Ansible to leverage the python code. In that case the roles indicated what each step is being executed and the data being manipulated. Since you are using the python code directly - we may need to figure out if fixing the log mechanism will work - or you could add print to the driver that is calling the ibmsecurity package? Open to ideas...

**Comment by dal-ibm** [comment]
Ahh yes, that would've been tricky. The "view it on GitHub" link in the email is my usual go-to.

Short-term, I think the Python script should log messages about the current action, and I'll port those across.

Long-term, if the additional data in Ansible scenarios is enough, is there some way for the library to distinguish between Ansible- and Python-invoked scenarios and add specifics for the Python code?

**Comment by ram-ibm** [comment]
Currently there is no way to distinguish a call to the Python code from the Ansible custom module versus running it directly. It can be added though - all calls from Ansible are routed via custom modules.

All output from the python code is currently using standard logger statements. So now the issue I am trying to figure out is how to write out the information that you are looking for? Do we continue using logger or output it someother way...

Could you clarify your thoughts on whether the driver code making the call to ibmsecurity can output print statements to plug this gap?

**Pull request merged**
