### PR TITLE
Added common_configuration call

### PR DESCRIPTION
**Pull request by hodon-sgibm**
While building a ISAM Automation, I have notice that the reverse proxy common configuration endpoint http request call was not provided. A similar structure of http request call was build for retrieving of reverse proxy common configuration json. 

However, if I do somehow miss out any existing approach of acquiring the configuration json, do correct me.

Thank you

### CODE REVIEW

**Comment by sygilber** [comment]
Hi

May I ask in what version of appliance this /wga/common_configuration end-point is available ? I use 9.0.3 and I can’t access it from lmi. Or maybe there is something i did not understood.

**Comment by hodon-sgibm** [comment]
Hi

The version I was testing on were 9.0.4, 9.0.0 and even 8.0.1.6. The common_configuration call would require you to provide the ISAM server as well as your reverseproxy id [get_all(isamAppliance, reverseproxy_id......)]. Eventual http calls would be directed to the reverseproxy's common_configuration endpoint(E.g: https://isam.myidp.ibm.com/wga/common_configuration/[reverseproxy_id]). 

For the UI simulation on accessing the endpoint, it is just clicking on the edit button after the selection of the reverseproxy from the list. 

Hopefully this helps.

Regards,

**Comment by ram-ibm** [comment]
The get_all() looks fine - but the get() needs to return an object formatted just like all other functions. use isamAppliance.create_return_object() and set the values into the "data" element before returning it please.

**Comment by hodon-sgibm** [comment]
Ok. Updated the common_configuration get()

**Comment by ram-ibm** [comment]
Please note that in the try catch you are still returning "False" which should be replaced by "return object".

**Comment by ram-ibm** [comment]
I will push changes that I made.

**Pull request merged**
