### PR TITLE
Issue 111

### PR DESCRIPTION
**Pull request by sygilber**
Provide support for additionnal parameters in 9.0.5.

### CODE REVIEW

**Comment by ram-ibm** [comment]
Reviewed these changes and the one that I am a concerned is the dynamicClient check. The function takes an "oidc" parameter. Typically the contents inside of the required data structure is left to the end-user. I am wondering if we need to stick to that - otherwise we may have to fix a fair bit of code to match this. Will get back on this.

**Comment by ram-ibm** [comment]
I made a number of changes to definitions.yml and reformatted admin.yml - I pushed it. Any chance you can test it out please? Otherwise I will need to see when I can test before merging.

**Comment by ram-ibm** [comment]
I am not convinced we are doing the right thing - too many edge cases that will mess this up. HEre is what I thought:

```
            if 'dynamicClients' in json_data['oidc']:
                if tools.version_compare(isamAppliance.facts["version"], "9.0.5.0") < 0:
                    warnings.append(
                        "Appliance at version: {0}, dynamicClients: {1} is not supported. Needs 9.0.5.0 or higher. Ignoring dynamicClients for this call.".format(
                            isamAppliance.facts["version"], json_data['oidc']['dynamicClients']))
                    del json_data['oidc']['dynamicClients']
            else:
                if 'dynamicClients' in ret_obj['data']['oidc'] and ret_obj['data']['oidc']['dynamicClients'] is False :
                    del ret_obj['data']['oidc']['dynamicClients']

            if 'issueSecret' in json_data['oidc']:
                if tools.version_compare(isamAppliance.facts["version"], "9.0.5.0") < 0:
                    warnings.append(
                        "Appliance at version: {0}, issueSecret: {1} is not supported. Needs 9.0.5.0 or higher. Ignoring issueSecret for this call.".format(
                            isamAppliance.facts["version"], json_data['oidc']['issueSecret']))
            else:
                if 'issueSecret' in ret_obj['data']['oidc'] and ret_obj['data']['oidc']['issueSecret'] is False :
                    del ret_obj['data']['oidc']['issueSecret']
```

I believe the way you fix this is to update your playbooks to pass False for these values to ensure Idempotency works. Deleting them may cause cases when it should either fail or show non-idempotent options to pass through undetected.

So I propose that if you are using v9.0.5 or higher then change your playbook to make sure that you are setting dynamicClients and issueSecret to be False. The playbook if run against a lower version will be taken care of by the code we have and for higher version will work as desired.

I propose the code to look like so:
```
            if 'dynamicClients' in json_data['oidc']:
                if tools.version_compare(isamAppliance.facts["version"], "9.0.5.0") < 0:
                    warnings.append(
                        "Appliance at version: {0}, dynamicClients: {1} is not supported. Needs 9.0.5.0 or higher. Ignoring dynamicClients for this call.".format(
                            isamAppliance.facts["version"], json_data['oidc']['dynamicClients']))
                    del json_data['oidc']['dynamicClients']

            if 'issueSecret' in json_data['oidc']:
                if tools.version_compare(isamAppliance.facts["version"], "9.0.5.0") < 0:
                    warnings.append(
                        "Appliance at version: {0}, issueSecret: {1} is not supported. Needs 9.0.5.0 or higher. Ignoring issueSecret for this call.".format(
                            isamAppliance.facts["version"], json_data['oidc']['issueSecret']))

```

**Comment by ram-ibm** [comment]
I pushed my proposed changes. Please review and let me know and I can merge to master.

**Comment by sygilber** [comment]
Hi, I completed some testing this evening with a fresh 9.0.4 VA.

a) Running with only 9.0.4 supported OIDC parameters (all fine)

*** Idempotency is preserved *** 

TASK [set_oauth_definition : Set a new OAuth 2.0 Definition some-api] ************************************************************************************************
ok: [someserver]


b) Running with 9.0.4 supported OIDC parameters AND the 2 new OIDC 9.0.5 parameters (OK):

*** As expected, a non-fatal warning is displayed for 'dynamicClients' and 'issueSecret', and idempotency is preserved *** 

TASK [set_oauth_definition : Set a new OAuth 2.0 Definition some-api] ************************************************************************************************
 [WARNING]: Appliance at version: 9.0.4.0, dynamicClients: True is not supported. Needs 9.0.5.0 or higher. Ignoring dynamicClients for this call.

 [WARNING]: Appliance at version: 9.0.4.0, issueSecret: False is not supported. Needs 9.0.5.0 or higher. Ignoring issueSecret for this call.

ok: [someserver]

c) Testing with 9.0.5 is fine also (creation and idempotency on successive runs of playbook).

**Comment by sygilber** [comment]
ok, I must re-test with different approach then. The previous results are from approach of this after noon.

**Comment by sygilber** [comment]
I'm striving to provide a code patch that is universal to all playbook version aiming at any of 9.0.3, 9.0.4, 9.0.5 without people needing to update "on-the-spot" their playbooks just because they upgraded to a more recent Appliance firmware. For some, idempotency is crucial.

The provided and tested code earlier does just that, but until we know better about the expected behavior by the Appliance if these 2 values are not passed, we can only make guesses.  Since the rest-api documentation is lacking the right level of details, let me check on clarifying them first. Please hold on if you can before merging this.

**Comment by ram-ibm** [comment]
I was going to suggest setting the default values in the role - but this is embedded in oidc parameter. Perhaps if you can confirm that dynamicClients and issueSecret are certainly FALSE by default then this code will work:
```
            if 'dynamicClients' in json_data['oidc']:
                if tools.version_compare(isamAppliance.facts["version"], "9.0.5.0") < 0:
                    warnings.append(
                        "Appliance at version: {0}, dynamicClients: {1} is not supported. Needs 9.0.5.0 or higher. Ignoring dynamicClients for this call.".format(
                            isamAppliance.facts["version"], json_data['oidc']['dynamicClients']))
                    del json_data['oidc']['dynamicClients']
            else:
                if 'dynamicClients' in ret_obj['data']['oidc'] and ret_obj['data']['oidc']['dynamicClients'] is False :
                    del ret_obj['data']['oidc']['dynamicClients']

            if 'issueSecret' in json_data['oidc']:
                if tools.version_compare(isamAppliance.facts["version"], "9.0.5.0") < 0:
                    warnings.append(
                        "Appliance at version: {0}, issueSecret: {1} is not supported. Needs 9.0.5.0 or higher. Ignoring issueSecret for this call.".format(
                            isamAppliance.facts["version"], json_data['oidc']['issueSecret']))
            else:
                if 'issueSecret' in ret_obj['data']['oidc'] and ret_obj['data']['oidc']['issueSecret'] is False :
                    del ret_obj['data']['oidc']['issueSecret']
```

We cannot remove the value for comparison unless the value is False for sure as default. Other values should trigger a compare.

**Comment by sygilber** [comment]
[issue_111_testresults.docx](https://github.com/IBM-Security/ibmsecurity/files/2484499/issue_111_testresults.docx)

The latest code proposal supports VA of previous version (before 9.0.5) as far as idempotency is concerned and supports going forward 9.0.5 and beyond. 

It takes into consideration testing results performed today that confirm that if a 9.0.5 VA does not receive during an **update** dynamicClients & issueSecret parameters, it will force them back to False if it was not already the case.

The code is not as compact as the previous proposal, but it does conform with the expected behavior.

**Comment by ram-ibm** [comment]
Merged.

**Pull request merged**
