### PR TITLE
Request to merger changes to master repository of IBMSecurity

### PR DESCRIPTION
**Pull request by bjsong19**
bug fix of attribute_source.py and new parameter support on api_protection/clients.py

### CODE REVIEW

**Comment by sygilber** [comment]
Hi, I believe that once PR 115 is merged, support for extProperties you be fulfilled.

**Comment by sygilber** [comment]
By the way, I was looking for what is the usage for the new extProperties in 9.0.5 ?

Looking forward for any insight, if anyone has found so far how to use it.

Cheers

**Comment by bjsong19** [comment]
Hello Silvain,

It will allow Partner provide more informations of the partner company
information on consent page such as their logo URL, license URL or
agreement URL etc. or any other information they want to show end user
before click deny or agree the asked scope.

It must be a valid JSON object, and will be used in mapping rule and
consent page.


Best regards

**Comment by ram-ibm** [comment]
Sylvain's code addresses some of what you did. I just merged his. There is one more pull request to process and then will get to this. Manual processing needed to resolve conflicts.

**Comment by ram-ibm** [comment]
extProperties are available now in the master branch.

**Pull request closed without merging**
