### PR TITLE
Provide candidate implementation for SNMP V3 Monitoring support

### PR DESCRIPTION
**Pull request by sygilber**
Please consider this piece for review and merge if judge satisfactory.

*** Addition of V3 support is written to be backward compatible ***

### CODE REVIEW

**Comment by ram-ibm** [comment]
This will work too - but I was looking to create a standard set() function like we have everywhere else that can handle the entire REST API call in one go. This is one of the very first - hence it does not have the ability to handle the entire parameter list and establish idempotency.

Conflicted if I should develop set() or merge your code for now and develop when I get more time...

**Comment by sygilber** [comment]
There is no rush to merge yesterday’s code. Let me rework it along your idea.

**Comment by sygilber** [comment]
Hi, so I reworked the code and tested it with both V1V2 and V3 settings this the latest commit. The role 'config_snmp_monitoring' is been adjusted accordingly on my end but will be submitted only after this PR is merged. 

Thanks

**Comment by ram-ibm** [comment]
I had in mind code that is more similar to the federation.set() function. I will work this and submit an update.

**Comment by sygilber** [comment]
Hello.

With SNMP, you can only add or remove an active SNMP Monitoring configuration. We cannot really add numerous of those. BUt here I am unsure then which part of the federation.set() I should follow as guideline.

**Comment by ram-ibm** [comment]
I created code - but indicated that it is draft since I did not get a chance to test it out thoroughly. Please note that ideally disable() and set_v1v2() should make a call to the set() I have coded.

**Comment by sygilber** [comment]
Will look into testing it this morning with V3 and V2.

**Comment by sygilber** [comment]
Hi

So in the last revision, we have:

-set_xx() and disable() all used internally the set() method as suggested.
-method disabled() moved up to regroup them all together and leave 'control' code at the bottom
-Added method set_v3() in case some still find it usefull

Results of of testing:

1. Test snmp_monitoring.py (20180717 commit) + set_v1v2 re-written as suggested with unmodified config_snmp_monitoring role to ADD a V2 configuration (OK)
2. Test snmp_monitoring.py (20180717 commit) + set_v1v2 re-written as suggested with unmodified config_snmp_monitoring role to UPDATE a V2 configuration (OK)
3. Test snmp_monitoring.py (20180717 commit) + set_v1v2 re-written as suggested with unmodified config_snmp_monitoring role to NOT UPDATE (idempotency validation) an existing V2 configuration (OK)
4. Test snmp_monitoring.py (20180717 commit) + disable re-written as suggested with unmodified config_snmp_monitoring role (OK)

So the updates are backward compatible with the current snmp_config_monitoring role, while allowing newer implementations of roles (v2v3 supported in the same role or 2 seperate roles).

Once this is reviewed and merge, based on your agreement, I will will rework the config_snmp_monitoring role. I have a mean to added support to V3 without breaking it.

**Comment by ram-ibm** [comment]
Looks good. Thanks for taking this on.

**Pull request merged**
