### PR TITLE
python 3 ... too soon

### LINKED ISSUE #344: Recent Update Breaks Configuration
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: invalid syntax (entry.py, line 26)
failed: [someappliance] (item={u'stanza_id': u'aznapi-configuration', u'entries': [[u'logcfg', u'audit.authn:rsyslog server=syslog,port=23500,log_id=someappliance-somewrp-audit,flush_interval=20,max_event_len=0,rebind_retry=3,queue_size=0,hi_water=1,error_retry=2'], [u'logcfg', u'http.clf:rsyslog server=syslog,port=someport,log_id=someserver-somewrp-http,flush_interval=20,max_event_len=0,rebind_retry=3,queue_size=0,hi_water=1,error_retry=2']]}) => {"ansible_loop_var": "item", "changed": false, "item": {"entries": [["logcfg", "audit.authn:rsyslog server=syslog,port=someport,log_id=someserver-somewrp-audit,flush_interval=20,max_event_len=0,rebind_retry=3,queue_size=0,hi_water=1,error_retry=2"], ["logcfg", "http.clf:rsyslog server=syslog,port=23501,log_id=someserver-somewrp-http,flush_interval=20,max_event_len=0,rebind_retry=3,queue_size=0,hi_water=1,error_retry=2"]], "stanza_id": "aznapi-configuration"}, "module_stderr": "Traceback (most recent call last):\n  File \"/home/sygilber/.ansible/tmp/ansible-local-109197Usddiy/ansible-tmp-1645796276.28-109962-9449687838271/AnsiballZ_isam.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/sygilber/.ansible/tmp/ansible-local-109197Usddiy/ansible-tmp-1645796276.28-109962-9449687838271/AnsiballZ_isam.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/sygilber/.ansible/tmp/ansible-local-109197Usddiy/ansible-tmp-1645796276.28-109962-9449687838271/AnsiballZ_isam.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.ibm.isam.plugins.modules.isam', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_ibm.isam.isam_payload_eCGdmm/ansible_ibm.isam.isam_payload.zip/ansible_collections/ibm/isam/plugins/modules/isam.py\", line 130, in <module>\n  File \"/tmp/ansible_ibm.isam.isam_payload_eCGdmm/ansible_ibm.isam.isam_payload.zip/ansible_collections/ibm/isam/plugins/modules/isam.py\", line 110, in main\n  File \"/tmp/ansible_ibm.isam.isam_payload_eCGdmm/ansible_ibm.isam.isam_payload.zip/ansible/module_utils/connection.py\", line 190, in __rpc__\nansible.module_utils.connection.ConnectionError: invalid syntax (entry.py, line 26)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: invalid syntax (entry.py, line 26)

Can someone please correct asap or rollback change ?

### PR DESCRIPTION
**Pull request by tombosmansibm**
Closes #344

### CODE REVIEW

**Comment by sygilber** [comment]
I would not say you are "too" soon with Python V3 ... once a leader we are now the one dragging behind )-:

**Comment by sygilber** [comment]
Testing you patch on this PR directly and the only remaining error is the following:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: Error> invalid action was specified, method not found in module!
failed: [someappliance] (item={u'stanza_id': u'header-names', u'entries': []}) => {"ansible_loop_var": "item", "changed": false, "item": {"entries": [], "stanza_id": "header-names"}, "module_stderr": "Traceback (most recent call last):\n  File \"/home/sygilber/.ansible/tmp/ansible-local-100450eh0nzo/ansible-tmp-1645799574.37-102736-13527176277094/AnsiballZ_isam.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/sygilber/.ansible/tmp/ansible-local-100450eh0nzo/ansible-tmp-1645799574.37-102736-13527176277094/AnsiballZ_isam.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/sygilber/.ansible/tmp/ansible-local-100450eh0nzo/ansible-tmp-1645799574.37-102736-13527176277094/AnsiballZ_isam.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.ibm.isam.plugins.modules.isam', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_ibm.isam.isam_payload_b6Jkey/ansible_ibm.isam.isam_payload.zip/ansible_collections/ibm/isam/plugins/modules/isam.py\", line 130, in <module>\n  File \"/tmp/ansible_ibm.isam.isam_payload_b6Jkey/ansible_ibm.isam.isam_payload.zip/ansible_collections/ibm/isam/plugins/modules/isam.py\", line 110, in main\n  File \"/tmp/ansible_ibm.isam.isam_payload_b6Jkey/ansible_ibm.isam.isam_payload.zip/ansible/module_utils/connection.py\", line 190, in __rpc__\nansible.module_utils.connection.ConnectionError: Error> invalid action was specified, method not found in module!\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by sygilber** [comment]
OK - seems the only remaining item to fix in this recent commit is the following which I do not think is a Python V2.7 vs V3.x issue. 

We have this code pattern all over place where we can obtain legitimaly '[]' while reading from external properties files and the previous Python code would just accept it:

        - { stanza_id: "acnt-mgt", entries: "[['some-entry','{{ lookup('ini', 'some-entry type=properties file={{ fact_rp_file }}') }}']]" }

I think we need to continue to support this pattern that keeps playbook clean without too much logic.

**Comment by tombosmansibm** [comment]
That seems wrong.  You have nested {{ }} :

Is it this ?
    - { stanza_id: "acnt-mgt", entries: "[['some-entry','{{ lookup('ini', 'some-entry type=properties file=fact_rp_file') }}']]" }

**Comment by tombosmansibm** [comment]
Works fine for me, by the way (Python 3.9).

Note that your initial syntax is not correct (nested {{ ).

```
instances:
  - inst_name: "default"
    entries:
      - method: set
        stanza_id: server
        entries:
          - [ "use-http-only-cookies", "no" ]
          - [ "allow-unsollicited-logins", "no" ]
  - inst_name: "default"
    entries:
      - method: set
        stanza_id: acnt-mgt
        entries:
          - [ "some-entry", "{{ lookup('ini', 'some-entry type=properties file=fact_rp_file') }}" ]
```
with a files/fact_rp_file .

TASK [ibm.isam.configure_reverseproxy_instances : Configure reverse proxy instances] ******************************************************************************************************************************************************************************************
vrijdag 25 februari 2022  16:38:18 +0100 (0:00:00.031)       0:00:00.366 ****** 
ok: [172.16.73.128] => (item={'method': set, inst_name: default, stanza_id: server, 'entries': ['use-http-only-cookies', 'no']['allow-unsollicited-logins', 'no']})
changed: [172.16.73.128] => (item={'method': set, inst_name: default, stanza_id: acnt-mgt, 'entries': ['some-entry', 'blablabla']})

**Comment by sygilber** [comment]
This code worked before as far as I can remember from 2017 to now.
Your proposal is to transform 1 line of code into 14 lines ?

**Comment by tombosmansibm** [comment]
No, my proposal is to NOT use nested {{}} (which I almost can't believe ever worked :-) ).  You can write it in one line as well.  I personally prefer yaml syntax everywhere:

```
  - inst_name: "default"
    entries:
      - {method: set, stanza_id: acnt-mgt, entries: [[ "some-entry", "{{ lookup('ini', 'some-entry type=properties file=fact_rp_file') }}" ]]}
 ```

**Comment by tombosmansibm** [comment]
I've installed a python 2.7 virtual env now , and this works fine:

```
TASK [ibm.isam.configure_reverseproxy_instances : Configure reverse proxy instances] ***************************************************
vrijdag 25 februari 2022  16:52:35 +0100 (0:00:00.015)       0:00:00.109 ****** 
ok: [172.16.73.128] => (item={'method': set, inst_name: default, stanza_id: server, 'entries': [u'use-http-only-cookies', u'no'][u'allow-unsollicited-logins', u'no']})
changed: [172.16.73.128] => (item={'method': set, inst_name: default, stanza_id: acnt-mgt, 'entries': [u'some-entry', u'blablabla2']})
```

**Comment by sygilber** [comment]
Tom, this specific item about the "{{}}" may be related to Python 2.7 vs Python 3.X as when re-write this line:

    rp_web_authn_methods: "{{ lookup('ini', 'web_authn_methods type=properties file={{ fact_rp_file }}') }}"

to 

    rp_web_authn_methods: "{{ lookup('ini', 'web_authn_methods type=properties file=fact_rp_file') }}"

i get other errors down the road.

I would just recommended for now for you to focus on the core issue which is the python code should consider as valid receiving an empty "[]".

**Comment by tombosmansibm** [comment]
Sorry, I see I've misinterpreted something.  fact_rp_file is obviously a variable, not the filename directly.


But both this syntax :
```
     - {method: set, stanza_id: acnt-mgt, entries: [[ "some-entry", "{{ lookup('ini', 'some-entry type=properties file='+fact_rp_file ) }}" ]]}
```

and this
```
      - {method: set, stanza_id: acnt-mgt, entries: [[ "some-entry", "{{ lookup('ini', 'some-entry type=properties file={{ fact_rp_file }}' ) }}" ]]}
```

both work for me, in Python 3 and Python 2.7.

**Comment by tombosmansibm** [comment]
OK, I've included a check for the "empty" value.

**Comment by ram-ibm** [comment]
The syntax Sylvain is referring to is in a lot of places (for entries with the nested []) - I really hope that does not break!

**Comment by tombosmansibm** [comment]
The issue here is that the value is empty (or rather, an empty []).  There’s no problem with the nested []…

**Comment by sygilber** [comment]
Tom. We are now finally on Python 3.6. Just wondering if you knew when this PR will review and merge d as we are observing the nested bug issue.

**Comment by tombosmansibm** [comment]
Not doing this anymore.  
Python 2.7 is no longer supported.

**Pull request closed without merging**
