### PR TITLE
V10.0.4 new features

### PR DESCRIPTION
**Pull request by tombosmansibm**
This is a first set of new features in v10.0.4. 

- update: add variable local_interface_only to web/runtime/process.py (new in v10.0.4)
- new: web/iag/export function for v10.0.4
- update: add detailed option to **get_all()** in web/reverse_proxy/junctions.py (new in v10.0.4)
- update: add parameter ignore_if_down to federated_directories (new in v10.0.4)
- new: testisam_cmd.py simple test script (accepts parameters)

#
#  web/iag/export
#
python testisam_cli.py --hostname 172.16.73.129 --method "ibmsecurity.isam.web.iag.export.get" --method_options "instance='default'"

python testisam_cli.py --hostname 172.16.73.129 --method "ibmsecurity.isam.web.iag.export.get_all"

python testisam_cli.py --hostname 172.16.73.129 --method "ibmsecurity.isam.web.iag.export.download" --method_options "instance='default',junctions=['/jct1'],features=['cors','change_inspector']"

#
# junctions detailed
#
python testisam_cli.py --hostname 172.16.73.129 --method "ibmsecurity.isam.web.reverse_proxy.junctions.get_all" --method_options "reverseproxy_id='default',detailed=True"

### CODE REVIEW

**Comment by Cedric-Ser** [comment]
Thank you for these changes Tom !

These are really valuables (as not always documented in the ISVA release notes). I do have some questions though, I see that you're introducing a new way of comparing dictionaries (by dumping them to string and comparing strings then), is this a new coding practice that will take place or .. ?

I see a bit of testing improvements in there too and I had a quick question about it too, if you plan to rewrite it, why don't you consider using unittest or pytest instead of that script ?

Regards,

Cédric S.

**Comment by tombosmansibm** [comment]
Hi Cedric,
pytest is indeed the goal, but I’ve not gotten there yet.  This was just a very small improvement to avoid having to store credentials in the tests and to be able to run a quick test without writing any code.
The comparison using json.dumps is what I will be using in the future, but the current way (in tools) will be around still.

**Comment by Cedric-Ser** [comment]
Thanks Tom,

One thing I tried locally, but without much success so far (or with very complex implementations) was to get what changed displayed at a glance. Typically, the user can figure out quickly the differences between these two:

```python
{'key_1': 'value_1', 'key_2': 'value_2'}
{'key_1': 'value_1', 'key_2': 'value_3'}
```

But it becomes much more complex as the dictionary gets bigger or with inner-structure. I've used the library (but that's yet another library to install) [jsondiff](https://github.com/xlwings/jsondiff) to generate these output. 

I don't know if that's easy to generalize though, I've only done it for junctions which was prolly one of the most complex idempotent check I had to generate,

Regards,

Cédric S.

**Comment by tombosmansibm** [comment]
That is correct , to be able to compare more complex structures, it's necessary to use a custom class in json.dumps.

**Pull request merged**
